# Generated by Django 5.2.8 on 2026-01-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience_alter_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed responsibilities and achievements'),
        ),
        migrations.AddField(
            model_name='experience',
            name='summary',
            field=models.CharField(blank=True, help_text='A short one-line catchphrase', max_length=255),
        ),
    ]
