# Generated by Django 5.2.8 on 2026-01-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_description_experience_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('tech_stack', models.CharField(help_text='Comma separated: Nextjs, TypeScript', max_length=200)),
                ('live_link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
