# Generated by Django 5.2.8 on 2026-01-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text="FontAwesome class, e.g., 'fas fa-code'", max_length=50)),
                ('description', models.TextField()),
                ('points', models.TextField(help_text='Separate points with new lines')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
